version: 1

formatters:
  simple:
    format: '%(asctime)s -  %(message)s in method %(funcName)s on line  %(lineno)d in file %(filename)s'
  error:
    format: '%(lineno)d | %(filename)s | %(asctime)s | '
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
  file:
    class: logging.FileHandler
    level: DEBUG
    filename: log.txt
    formatter: error
loggers:
  simpleExample:
    level: DEBUG
    handlers: [console, file]

