version: 1

formatters:
  simple:
    format: '| %(asctime)s | %(levelname)s | %(message)s | %(funcName)s | %(lineno)d | %(filename)s |'
  warning:
    format: '| %(asctime)s | %(levelname)s | %(message)s | %(funcName)s | %(lineno)d | %(filename)s |'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
  file_warning:
    class: logging.FileHandler
    level: WARNING
    filename: log_warning.txt
    formatter: warning
loggers:
  simpleExample:
    level: INFO
    handlers: [console, file_warning]

