version: 1

formatters:
  simple:
    format: '%(asctime)s -  %(message)s in method %(funcName)s on line  %(lineno)d in file %(filename)s'
  warning:
    format: '%(asctime)s | %(levelname)s | %(message)s | %(lineno)d | %(filename)s |'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
  file_warning:
    class: logging.FileHandler
    level: WARNING
    filename: log_warning.txt
    formatter: warning
loggers:
  simpleExample:
    level: WARNING
    handlers: [console, file_warning]

